env:
  global:
  - SWIFT_BRANCH=swift-4.2-branch
  - SWIFT_VERSION=swift-4.2-DEVELOPMENT-SNAPSHOT-2018-05-30-a

sudo: required

script:
    - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"
    - swift package update
    - swift build --product builder
    - ".build/debug/builder build"
    - ".build/debug/xpkg --version"
    - ".build/debug/builder test"

matrix:
  include:
  - os: linux
    dist: trusty
    language: generic
    install:
    - sudo apt-get install clang libicu-dev
    - mkdir swift
    - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz
      -s | tar xz -C swift &> /dev/null
  - os: osx
    osx_image: xcode9.3
    language: swift
    install:
    - wget https://swift.org/builds/$SWIFT_BRANCH/xcode/$SWIFT_VERSION/$SWIFT_VERSION-osx.pkg
    - sudo installer -pkg $SWIFT_VERSION-osx.pkg -target /


notifications:
  email: false
  slack:
    rooms:
      secure: soh6OcjOfQmamDQBFSET9z95ROkk8mhC9DANX0WYMucAeFu+bvm3DJsilU4MauHwmXVr33IeyoF48QNuOUY8o92KfVO787y9lvS06SFcb27Mw9TE36ws7ZYLlODJ90G9rkfeExVuiguiDY+7g3z5DonVyJ07CROYijrv3x0RB0pVV8ShK6OHYUNPnB5Ce9nDdglIRNYNb9zytT4qzj2X0TySQspEMQosdwbWktbtECE7CK80uLiaKHAa2h3YBaoNvmR9Z2G4VGD/tR8frkV6JhWIMnwm2yA1yWwBi2lT3wtFZ79VRSwkUgRgvb8XhnGUgc0/3+/X7YWK4+fSRMDIIjg+0kTtTuC3XQDrFzBwj7xW2OSEqOMKna5GmwvA/Sspit55BeH4rC49MGWbnEvtksar2E172MCyfH4X2KqjkVytWCkbzY2PdvNqwgFH8lnJfEFEB1Yp+5zeXCepEYUb8yD0Lx97ggrIWEOFfQOIGtpX8FBj/q+oPEeYymvl8FY1oceCt6wAj0YiePFb0XqWqSPFHUwhaNYJ9wb9dgIf1rX51XrGSandpYfjmtJjKb0G5kgP3cMx9OutdqL1wqGWSMdRPd9c+NwoTaZGNfdcao7DjtKYahSzA6f6ZBnRs+CaVLfpBhy1YCRjhCpJyCSJf9EbGkVaJDMBoiuwI2UHQcY=
