env:
  global:
  - SWIFT_BRANCH=swift-4.2-branch
  - SWIFT_VERSION=swift-4.2-DEVELOPMENT-SNAPSHOT-2018-05-30-a
matrix:
  include:
  - os: linux
    language: generic
    dist: trusty
    sudo: required
    install:
    - sudo apt-get install clang libicu-dev
    - mkdir swift
    - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz
      -s | tar xz -C swift &> /dev/null
    - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"
    - swift package update
    script:
    - swift run builder test
    - swift run builder run --version
  - os: osx
    osx_image: xcode9.3
    language: swift
    sudo: required
    install:
    - wget https://swift.org/builds/$SWIFT_BRANCH/xcode/$SWIFT_VERSION/$SWIFT_VERSION-osx.pkg
    - sudo installer -pkg $SWIFT_VERSION-osx.pkg -target /
    - export PATH="/Library/Developer/Toolchains/$SWIFT_VERSION.xctoolchain/usr/bin:$PATH"
    - swift package update
    script:
    - swift run builder test
    - swift run builder run --version
notifications:
  email: false
  slack:
    rooms:
      secure: lOS0PeJ0l4D3Onb0NhnI8ceADW5lQgP5sVjw3hXZmPdlPiBKUpWeu2nGK6uL7muI76RuctHFM1xCPIChpHcNcAj8HtEXZwx5Ja8Dcbm3wCFzMiFdfEqY5l/NlcK7PHSv1cLUMDJlj2kz0VRY2YTaKjMGqgtvtLBrNmB8y6mSzHLRyhpOfEtB7HPDbCK+YF/gkA28NnJ0HlFBqMFU558+yCqJuUOBZVJjI9cKpQR0Oaxq/A1VS/v8jn24CsWSnsjxKJqOQ8W9WDA1n9oFJNbi5fiwQjAtR6x5o4IZjdNZQFR6y6qU/p/Ao3k+fH8xUrLxQeE4h8erKh+7szdYMVQx8fKycVAJKPY6c/wYGi9Wb4THDPwOrJ/vsUrOaU73iRf0NkteMZ8Nv/+SxM60UYWoO1+p/zk6jxWSvZ4u4jDPROlI+naoQyO5vgPi2j+WusF+5plG7FKt4EOOfGcezMPC4r+HHuWvYJz2tCJqY4UCoDZK3s6Pee6ICcp9ARoBfBdoHmt82kqq3/YqCyxNR/v7QQZ33ptiF3rcoD0B8GA+rrgP1T2vj+E1NQDsHjjTcMHqhUx9lKwL1sSIz7Jy1kXwWkoGSNbGqlJi07nuU+3vtBOde6M0ZVG0FrzQzpkYXAdnhlVHe3HQZ/VQ1QJ4iHodW6VxrO3Vxw09g0RLPTgD0aQ=
