#!/usr/local/bin/fish

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Created by Sam Deane on 26/03/2020.
#  All code (c) 2020 - present day, Elegant Chaos Limited.
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

set -x SHELL_HOOKS_SHELL fish
set -x SHELL_HOOKS_RC 1
set -x SHELL_HOOKS_PLATFORM (uname)
set -x SHELL_HOOKS_ROOT "$HOME/.local/share/shell-hooks"
set -x SHELL_HOOKS_INTERACTIVE 1

fish_add_path "$HOME/.local/bin"
