#!/bin/bash

ROOT="$HOME/.config/xpkg"
mkdir -p "$ROOT"
cd "$ROOT"
git clone https://github.com/elegantchaos/xpkg.git code
cd code
swift build

LOCALBIN=~/.local/bin

if [[ -e "$LOCALBIN" ]]
then
    ln -s "$ROOT/code/.build/debug/xpkg" "$LOCALBIN/xpkg"
else
    sudo ln -s "$ROOT/code/.build/debug/xpkg" "/usr/local/bin/xpkg"
fi
