#!/bin/bash

ROOT="$HOME/.config/xpkg"

if [[ -e "$ROOT/code" ]]
then
    echo "Updating xpkg."
    cd "$ROOT/code"
    git pull
else
    echo "Downloading xpkg."
    mkdir -p "$ROOT"
    cd "$ROOT"
    git clone https://github.com/elegantchaos/xpkg.git code
    cd code
fi

source "$ROOT/.bin/install"
