#!/bin/bash

ROOT="$HOME/.local/share/xpkg"

if [[ -e "$ROOT/code" ]]
then
    echo "Updating xpkg."
    cd "$ROOT/code"
    git pull
else
    echo "Downloading xpkg."
    mkdir -p "$ROOT"
    cd "$ROOT"
    git clone https://github.com/elegantchaos/Xpkg.git code
    cd code
fi

if [[ $? == 0 ]]
then
    source "$ROOT/code/.bin/install"
fi
