#!/bin/bash

ROOT="$HOME/.local/share/xpkg"

echo "Building."
swift run builder build
if [[ $? != 0 ]]
then
    echo "Build failed."
    exit 1
fi

FISH="$HOME/.config/fish/functions"

LOCAL="$HOME/.local"
echo "Installing links."
if [[ -e "$LOCAL" ]]
then
    STARTUP="$LOCAL/share/shell-hooks/startup"
    BIN="$LOCAL/bin"
    SUDO=
else
    STARTUP="/usr/local/share/shell-hooks/startup"
    BIN="/usr/local/bin"
    SUDO=sudo
fi

$SUDO mkdir -p "$STARTUP"
$SUDO ln -sf "$ROOT/code/.bin/xpkg-bash" "$STARTUP/xpkg"
$SUDO mkdir -p "$BIN"
$SUDO ln -sf "$ROOT/code/.build/debug/xpkg" "$BIN/xpkg"
mkdir -p "$FISH"
ln -sf "$ROOT/code/.bin/xg.fish" "$FISH/xg.fish"

echo "Installing essential packages."

~/.local/bin/xpkg install elegantchaos/shell-hooks
~/.local/bin/xpkg install samdeane/settings-shell

echo "Done."
