#!/bin/bash


ROOT="$HOME/.local/share/xpkg"

echo "Building."
swift run builder build
if [[ $? != 0 ]]
then
    echo "Build failed."
    exit 1
fi

FISH="$HOME/.config/fish/functions"

LOCAL="$HOME/.local"
echo "Installing links."
if [[ -e "$LOCAL" ]]
then
    echo "Performing local installation."
    export STARTUP="$LOCAL/share/shell-hooks/startup"
    export BIN="$LOCAL/bin"
    export SUDO=
else
    echo "Performing global installation (requires sudo)."
    export STARTUP="/usr/local/share/shell-hooks/startup"
    export BIN="/usr/local/bin"
    export SUDO=sudo
fi

echo "bin is $BIN."
echo "startup is $STARTUP."

$SUDO mkdir -p "$STARTUP"
$SUDO ln -sf "$ROOT/code/.bin/xpkg-bash" "$STARTUP/xpkg"

$SUDO mkdir -p "$BIN"
$SUDO ln -sf "$ROOT/code/.build/debug/xpkg" "$BIN/xpkg"
$SUDO ln -sf "$ROOT/code/.bin/uninstall" "$BIN/xpkg-uninstall"

mkdir -p "$FISH"
ln -sf "$ROOT/code/.bin/xg.fish" "$FISH/xg.fish"

echo "Installing shell startup hooks."
$SUDO "$ROOT/code/.bin/shell-hooks/install" "$ROOT"

echo "Done."
