
if [[ "$SHELL_HOOKS_RC" == "" ]]
then

export SHELL_HOOKS_SHELL="bash"
export SHELL_HOOKS_RC=1
export SHELL_HOOKS_PLATFORM=`uname`
export SHELL_HOOKS_ROOT="$HOME/.local/share/shell-hooks"

# legacy
export BASH_HOOKS_RC=1
export BASH_HOOKS_PLATFORM=`uname`
export BASH_HOOKS_ROOT="$HOME/.local/share/shell-hooks"

# Source a hook
# Before sourcing, we change the working directory to the true
# location of the hook file. This allows hooks to reference other
# local resources just using ./my-resource
function source_hook() {
  absolute=$(readlink "$1")
  container=$(dirname "$absolute")
  pushd "$container" > /dev/null
  source "$absolute"
  popd > /dev/null
}

# Source each hook in a folder.
function source_hooks() {
  FOLDER=$1
  if [[ -e "$FOLDER" ]]
  then
      for f in "$FOLDER"/*
      do
          source_hook $f
      done
  fi
}

export -f source_hook
export -f source_hooks

source_hooks "$SHELL_HOOKS_ROOT/startup"
source_hooks "$SHELL_HOOKS_ROOT/startup-$SHELL_HOOKS_PLATFORM"

if [[ -e "$HOME/.bashrc.backup" ]]
then
    source "$HOME/.bashrc.backup"
fi

# If not running interactively exit now
case $- in
    *i*) ;;
      *) return;;
esac

export BASH_HOOKS_INTERACTIVE=1
source_hooks "$SHELL_HOOKS_ROOT/interactive"
source_hooks "$SHELL_HOOKS_ROOT/interactive-$SHELL_HOOKS_PLATFORM"

fi
