#if !canImport(ObjectiveC)
import XCTest

extension XPkgTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XPkgTests = [
        ("testName", testName),
        ("testNameOrg", testNameOrg),
        ("testRepo", testRepo),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XPkgTests.__allTests__XPkgTests),
    ]
}
#endif
