#!/bin/bash

ROOT="$HOME/.local/share/xpkg"

if [[ -e "$ROOT/code" ]]
then
    echo "Updating xpkg."
    cd "$ROOT/code"
    git pull
    XPKG_INSTALL_MODE="--no-backup"
else
    echo "Downloading xpkg."
    mkdir -p "$ROOT"
    cd "$ROOT"
    git clone https://github.com/elegantchaos/XPkg.git code
    cd code
    git checkout development # TODO: remove this
fi

if [[ $? == 0 ]]
then
    source "$ROOT/code/Extras/Scripts/install"
fi
